traffic:
  outputs:

    dev:
      type: postgres
      threads: 10
      host: host.docker.internal
      port: 5432
      user: airflow
      pass: airflow
      dbname: postgres
      schema: public

    prod:
      type: postgres
      threads: 10
      host: host.docker.internal
      port: 5432
      user: airflow
      pass: airflow
      dbname: postgres
      schema: public
      
  target: dev


pneuma_data:

  outputs:
    dev:
      type: postgres
      threads: 10
      host: host.docker.internal
      port: 5432
      user: airflow
      pass: airflow
      dbname: postgres
      schema: public

    prod:
      type: postgres
      threads: 10
      host: 127.0.0.1
      port: 2000
      user: postgres
      pass: root
      dbname: traffic_data
      schema: public

  target: dev
